# Copyright 2026 The TrustList Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The evidence-writer service stub (Stage 0 PRD §7b consumer, §8.2 round-trip).

PRD §7b names an *evidence-writer service* as a consumer of the
``signal.tier-one.*`` topics; PRD §8 acceptance criterion 2 requires that a
synthetic tier-one signal event, produced to ``signal.tier-one.example-collector``,
is read by that consumer and persisted to the canonical store as one
``evidence`` row referencing one ``provenance`` row.

This module is the Stage-0-scoped *stub* of that service. The full
evidence-writer — back-pressure tuning, partition-rebalance handling, the
durable consumer-side dedup store of PRD §7a ``output_cache`` — is a
later-stage deliverable. The stub implements exactly the §8.2 contract:

1. Decode the tier-one signal envelope (the event-bus SDK already did this).
2. In one database transaction (PRD §7a forbids batch transactions across
   *observations* — a single observation's provenance+evidence pair is one
   write unit, which is what a transaction here represents):
   a. ensure the observed ``domain`` row exists;
   b. write one ``provenance`` row from the envelope's ``provenance`` field;
   c. write one ``evidence`` row referencing that provenance row, carrying the
      synthetic payload's observation.
3. Commit.

**Idempotency.** PRD §8 criterion 5 requires the smoke test to be idempotent:
re-running it produces the same final canonical-store state. The event-bus
SDK's :class:`~trustlist_event_bus.consumer.InMemoryDedupStore` deduplicates
*within a process*, but it does not survive a restart, and re-running the smoke
test is precisely a fresh process. So the writer also deduplicates *at the
database*: before inserting, it looks for an ``evidence`` row already carrying
this event's ``idempotency_key`` (stamped into ``provenance.method`` as a
stable, queryable anchor). When one exists, the write is skipped and the
existing rows are returned. The canonical store therefore converges to exactly
one provenance+evidence pair per logical signal, no matter how many times the
event is delivered or the harness is re-run.

Append-only discipline (PRD §7a) is respected throughout: the writer only ever
INSERTs into ``provenance`` and ``evidence`` — it never UPDATEs or DELETEs — so
it runs cleanly under the restricted ``trustlist_app`` role.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from sqlalchemy import text
from sqlalchemy.engine import Connection, Engine

from observability import get_logger, instrument_consume
from trustlist_event_bus import EventEnvelope

# The ``provenance.method`` value is free text in the §7a schema. The writer
# uses it to carry a stable, queryable idempotency anchor for the stub: the
# method label plus the event's idempotency key. Querying for this prefix on a
# JOIN through ``evidence`` is what makes the database-level dedup work.
_METHOD_PREFIX = "evidence-writer-stub"

_LOG = get_logger("evidence-writer-stub")


@dataclass(frozen=True, slots=True)
class WriteResult:
    """The outcome of handling one tier-one signal event.

    :ivar provenance_id: the ``provenance`` row's UUID — the existing row when
        the event was a duplicate, the freshly-inserted row otherwise.
    :ivar evidence_id: the ``evidence`` row's UUID, by the same rule.
    :ivar domain_id: the ``domain`` row's UUID the evidence concerns.
    :ivar created: ``True`` when this call inserted new rows; ``False`` when the
        event was recognised as an already-persisted duplicate and skipped.
    """

    provenance_id: str
    evidence_id: str
    domain_id: str
    created: bool


def _idempotency_method(idempotency_key: str) -> str:
    """Return the ``provenance.method`` value carrying the idempotency anchor.

    The format is ``"<prefix>:<idempotency_key>"`` — a single text column that
    is both human-readable in the canonical store and exact-match queryable for
    the database-level deduplication.
    """
    return f"{_METHOD_PREFIX}:{idempotency_key}"


def _ensure_domain(conn: Connection, domain_id: str, normalised_url: str) -> str:
    """Ensure a ``domain`` row exists for ``domain_id``; return its id.

    The synthetic signal carries a ``domain_id`` (a UUID) generated by the
    harness. The smoke test owns its own domain rather than depending on one
    being pre-seeded, so the writer inserts the domain when absent. The insert
    is a no-op on a re-run (``ON CONFLICT DO NOTHING`` on the primary key),
    which keeps the writer idempotent on the domain row too.

    The ``normalised_url`` is derived from the ``domain_id`` so it satisfies the
    ADR-0002 ``normalised_url`` CHECK constraint (lowercase, no scheme, no
    ``www.``, no query/fragment, no whitespace) deterministically.
    """
    existing = conn.execute(
        text("SELECT domain_id FROM domain WHERE domain_id = :id"),
        {"id": domain_id},
    ).scalar()
    if existing is not None:
        return str(existing)
    conn.execute(
        text(
            "INSERT INTO domain (domain_id, normalised_url, current_status) "
            "VALUES (:id, :url, 'under_review') "
            "ON CONFLICT (domain_id) DO NOTHING"
        ),
        {"id": domain_id, "url": normalised_url},
    )
    return domain_id


def _find_existing(conn: Connection, idempotency_key: str) -> WriteResult | None:
    """Return the already-persisted pair for ``idempotency_key``, or ``None``.

    A previous delivery (or a previous run of the smoke test) may already have
    written this exact logical signal. The lookup joins ``evidence`` to
    ``provenance`` on the idempotency-anchored ``provenance.method`` value; a
    hit means the canonical store already holds this signal and the write must
    be skipped to stay idempotent (PRD §8 criterion 5).
    """
    row = conn.execute(
        text(
            "SELECT e.evidence_id, e.provenance_id, e.domain_id "
            "FROM evidence e JOIN provenance p "
            "  ON p.provenance_id = e.provenance_id "
            "WHERE p.method = :method"
        ),
        {"method": _idempotency_method(idempotency_key)},
    ).one_or_none()
    if row is None:
        return None
    return WriteResult(
        provenance_id=str(row.provenance_id),
        evidence_id=str(row.evidence_id),
        domain_id=str(row.domain_id),
        created=False,
    )


def write_evidence(engine: Engine, envelope: EventEnvelope) -> WriteResult:
    """Persist one tier-one signal event as a provenance+evidence pair.

    This is the core of the evidence-writer stub — the body the consumer
    handler runs for every event. It is transactional and idempotent:

    - the whole write happens in one transaction, so a failure leaves the
      canonical store untouched (no orphan ``provenance`` row);
    - a re-delivery, or a re-run of the smoke test, is recognised by the
      idempotency anchor and returns the existing rows without inserting.

    :param engine: a SQLAlchemy engine bound to the migrated canonical store.
    :param envelope: the decoded tier-one signal envelope, carrying the
        synthetic ``payload`` and the §7a ``provenance`` triple.
    :returns: a :class:`WriteResult` naming the persisted (or pre-existing)
        ``provenance``, ``evidence`` and ``domain`` rows.
    :raises KeyError: when the payload is missing a required field — the
        synthetic schema (``event-schema/signal.tier-one.example-collector``)
        was already validated by the SDK on consume, so this is defensive.
    """
    payload = envelope.payload
    domain_id = str(payload["domain_id"])
    signal_class = str(payload["signal_class"])
    source_url = str(payload.get("source_url", ""))
    observed_at = str(payload["observed_at"])
    observed_value = payload["observed_value"]
    idempotency_key = envelope.idempotency_key
    provenance = envelope.provenance

    # The ADR-0002-normalised URL for the synthetic domain. The domain_id is a
    # UUID; "<uuid>.smoke.trustlist.test" is lowercase, scheme-free, www-free,
    # query/fragment-free and whitespace-free, so it passes the CHECK.
    normalised_url = f"{domain_id}.smoke.trustlist.test"

    with engine.begin() as conn:
        # Database-level deduplication first: a hit means the canonical store
        # already holds this exact signal, so this is a no-op (idempotency).
        existing = _find_existing(conn, idempotency_key)
        if existing is not None:
            _LOG.info(
                "evidence-writer skipped a duplicate signal",
                idempotency_key=idempotency_key,
                evidence_id=existing.evidence_id,
            )
            return existing

        _ensure_domain(conn, domain_id, normalised_url)

        # One provenance row. The idempotency key is carried in `method` as the
        # stable anchor the dedup query above matches on.
        provenance_id = conn.execute(
            text(
                "INSERT INTO provenance "
                "(source, method, observed_at, contributor_identity) "
                "VALUES (:source, :method, :observed_at, :contributor) "
                "RETURNING provenance_id"
            ),
            {
                "source": provenance.source,
                "method": _idempotency_method(idempotency_key),
                "observed_at": observed_at,
                "contributor": provenance.contributor_identity,
            },
        ).scalar_one()

        # One evidence row referencing that provenance row.
        evidence_id = conn.execute(
            text(
                "INSERT INTO evidence "
                "(domain_id, signal_class, source, method, source_url, "
                " observed_at, observed_value, provenance_id) "
                "VALUES (:domain_id, :signal_class, :source, :method, "
                "        :source_url, :observed_at, "
                "        CAST(:observed_value AS jsonb), :provenance_id) "
                "RETURNING evidence_id"
            ),
            {
                "domain_id": domain_id,
                "signal_class": signal_class,
                "source": provenance.source,
                "method": provenance.method,
                "source_url": source_url,
                "observed_at": observed_at,
                "observed_value": json.dumps(observed_value),
                "provenance_id": str(provenance_id),
            },
        ).scalar_one()

    _LOG.info(
        "evidence-writer persisted a tier-one signal",
        idempotency_key=idempotency_key,
        domain_id=domain_id,
        evidence_id=str(evidence_id),
        provenance_id=str(provenance_id),
    )
    return WriteResult(
        provenance_id=str(provenance_id),
        evidence_id=str(evidence_id),
        domain_id=domain_id,
        created=True,
    )


class EvidenceWriter:
    """The evidence-writer stub as a callable event-bus consumer handler.

    An instance is the handler passed to
    :meth:`trustlist_event_bus.EventConsumer.run`. It binds the canonical-store
    engine once and, for each consumed envelope, runs :func:`write_evidence`
    and records the :class:`WriteResult` so the test harness can assert on it.

    The :meth:`handle` method is wrapped with
    :func:`observability.instrument_consume`, which reads the W3C trace context
    out of the envelope and parents the consumer span to the producer's trace —
    so a signal's collector → bus → consumer flow is one distributed trace
    (PRD §7f, ADR-0012). The span verification is locally observable via an
    in-memory span exporter; export to Honeycomb is deferred until the
    observability platform is wired (no account yet).
    """

    def __init__(self, engine: Engine) -> None:
        """Bind the writer to the canonical-store ``engine``."""
        self._engine = engine
        self._results: list[WriteResult] = []

    @property
    def results(self) -> list[WriteResult]:
        """The :class:`WriteResult` of every event handled so far, in order."""
        return list(self._results)

    def __call__(self, envelope: EventEnvelope) -> None:
        """Handle one consumed envelope — the event-bus handler entry point."""
        # The consume span is parented to the producer's trace via the
        # envelope's W3C trace_context carrier.
        self.handle(envelope, carrier=envelope.trace_context)

    @instrument_consume("evidence-writer.handle")
    def handle(
        self,
        envelope: EventEnvelope,
        *,
        carrier: dict[str, str],
    ) -> WriteResult:
        """Persist one envelope and record its result.

        :param envelope: the decoded tier-one signal envelope.
        :param carrier: the W3C trace-context carrier — the envelope's
            ``trace_context`` field. ``instrument_consume`` consults it to
            parent the consumer span to the producer's trace.
        :returns: the :class:`WriteResult` for this event.
        """
        result = write_evidence(self._engine, envelope)
        self._results.append(result)
        return result
